version: 2

models:
  - name: dim_people
    description: "persons who are assigned to tasks"
    columns:
       - name: person_id
         data_type: integer
         description: "primary key for person"
       - name: person_name
         data_type: character varying
         description: "stored name of the person"
  - name: dim_tasks
    description: "tasks that are assigned to people, with recurrence patterns"
    columns:
      - name: task_id
        data_type: integer
        description: "primary key for task"
      - name: task_name
        data_type: character varying
        description: "stored name of the task"
      - name: cadence
        data_type: character varying
        description: "recurrence pattern (daily, weekly, monthly)"
      - name: start_date
        data_type: date
        description: "date when the task starts"
      - name: max_occurrences
        data_type: integer
        description: "maximum number of occurrences for the task"
  - name: fct_task_occurrences
    description: "fact table that generates task occurrences based on the tasks and their recurrence patterns, and tracks the status of each occurrence over time"
    columns:
      - name: task_occurrence_id
        data_type: text
        description: "primary key for task occurrence, generated as task_id + occurrence_number"
      - name: task_id
        data_type: integer
        description: "primary key for task from dim_tasks"
      - name: task_name
        data_type: character varying
        description: "stored name of the task from dim_tasks, denormalized for easier querying"
      - name: person_id
        data_type: integer
        description: "primary key for person from dim_people, assigned to this task occurrence"
      - name: person_name
        data_type: character varying
        description: "stored name of the person from dim_people, denormalized for easier querying"
      - name: occurrence_number
        data_type: integer
        description: "occurrence number for this task, starting at 1 and incrementing based on the cadence and start_date of the task"
      - name: occurrence_date
        data_type: timestamp without time zone
        description: "date and time when this task occurrence is scheduled to occur, calculated based on the cadence and start_date of the task"
      - name: status
        data_type: character varying
        description: "current status of the task occurrence ('not started', 'in progress', 'completed')"
      - name: last_updated
        data_type: timestamp with time zone
        description: "timestamp of the last update to this task occurrence, used for tracking when status changes occur"
      - name: is_completed
        data_type: integer
        description: "boolean flag (0 or 1) indicating whether the task occurrence is completed, used for easier filtering in queries"
  - name: bridge_task_occurrence_assignments
    description: " bridge table to handle many-to-many relationships between task occurrences and people, in case a task occurrence can be assigned to multiple people or a person can have multiple task occurrences"
    columns:
      - name: task_occurrence_id
        data_type: text
        description: "primary key for task occurrence from fct_task_occurrences, indicating which task occurrence is being assigned"
      - name: person_id
        data_type: integer
        description: "primary key for person from dim_people, indicating which person is assigned to this task occurrence"