name: 'chorus_data_engineer_interview'
version: '1.0.0'
profile: 'chorus_data_engineer_interview'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  chorus_data_engineer_interview:
    staging:
      +materialized: view
      tags: ["staging"]
    marts:
      core:
        +materialized: table
        tags: ["marts", "core"]
