chorus_data_engineer_interview:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: user
      password: password
      dbname: postgres
      schema: public
      threads: 4
      keepalives_idle: 0
